name: Bug 反馈
description: 在使用 ClassIsland 的过程中遇到了 Bug。
title: （在这里输入你的标题）
labels: ["Bug"]
body:
  - type: markdown
    attributes:
      value: |
        感谢您进行 Bug 反馈。请在上面的文本框⬆️起一个能够清晰描述您的问题的标题，便于开发者解决您的问题。
        
        > 重要：如果要提出**多个 Bug**，请为每一个 Bug 开一个单独的 issue。
        
        > 如果您不知道如何有效、精准地表述，我们建议您先阅读《提问的智慧》（[链接](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md)）。
        
        ### 在开始之前，请先检查：
        
        - [x] 我已更新到最新版 ![最新的版本号](https://img.shields.io/github/v/release/ClassIsland/ClassIsland?include_prereleases&style=flat-square&label=) 或 ![最新的版本号](https://img.shields.io/github/v/release/ClassIsland/ClassIsland?style=flat-square&label=)测试，并看过 [最新提交](https://github.com/ClassIsland/ClassIsland/commits/dev/)，确认这一 Bug 还没有修复
        - [x] 我已在 [Issues](https://github.com/ClassIsland/ClassIsland/issues?q=label%3ABug) 和 [常见问题](https://docs.classisland.tech/zh-cn/latest/app/faq/) 中检索，确认这一 Bug 未被提交过
        - [x] 我已知晓并同意，此处仅用于汇报程序中存在的问题（关于其他非程序本身问题应当在 Discussion 板块提出）
        - [x] 我使用的系统版本为 Windows 10 / 11（开发者不会受理 Windows 7 系统相关问题）
  - type: markdown
    attributes: 
      value: |
        ### Bug 信息

        描述您遇到的 Bug。您可以附上截图、录屏、堆栈跟踪、日志等材料，便于开发者追踪问题。
  - type: textarea
    id: what-happened
    attributes:
      label: 描述
      description: 详细描述该 Bug 的具体表现。
    validations:
      required: true
  - type: textarea
    id: reproduce-steps
    attributes:
      label: 重现步骤
      description: |
        详细描述要怎么操作才能再次触发这个 Bug。
      placeholder: |
        1. 首先……
        2. 然后……
        3. ……
    validations:
      required: true
  - type: textarea
    id: stacktrace
    attributes:
      label: 堆栈跟踪（可选）
      description: 如果在遇到这个 bug 时发生了崩溃（弹出崩溃提示），或者产生了错误日志，请将产生的堆栈跟踪信息粘贴到此处，便于定位 bug。
      render: shell
  - type: input
    id: os_version
    attributes:
      label: 操作系统版本
      description: |
        您当前使用的 Windows 操作系统版本，可以运行 `winver.exe` 查看。
        如果您不能肯定此 Bug 与操作系统无关，请填写此项。
      placeholder: 如：10.0.22000.0
  - type: markdown
    attributes:
      value: |
        ### 版本号确认
        
        - [x] 我确认 ClassIsland 版本号为 ![最新的版本号](https://img.shields.io/github/v/release/ClassIsland/ClassIsland?include_prereleases&style=flat-square&label=)
        - [x] 我确认运行 ClassIsland 的操作系统为 Windows 10 或 11，而不是 Windows 7
        
        ### 最后一步：回顾您的表述
        
        - [x] 我认为上述的描述已经足够详细，以允许开发人员能复现该问题。
