name: 功能请求
description: 提出一项新的功能。
title: （在这里输入你的标题）
labels: ["新功能"]
body:
  - type: markdown
    attributes:
      value: |
        感谢您贡献您的想法。请在上面的文本框⬆️起一个能够清晰概括此功能的标题，便于开发者了解您的想法。

        > 重要：如果您想要提出 **多项功能**，请为每一个功能开一个单独的 issue。
        
        ### 在开始之前，请先检查：
      
        - [x] 我已经将本应用更新到最新测试版 ![最新的版本号](https://img.shields.io/github/v/release/ClassIsland/ClassIsland?include_prereleases&style=flat-square&label=)，确认我想要的功能没有实现
        - [x] 我已经在 [Issues](https://github.com/ClassIsland/ClassIsland/issues?q=label%3A新功能) 中找过我要提出的功能，没有找到相同的功能请求（如已有类似的请求，请直接回复该 issue 进行补充）
        - [x] 我阅读了 [ClassIsland 文档](https://docs.classisland.tech/zh-cn/latest/app/)，确认我想要的功能没有实现
        - [x] 我确认我要提出的功能尚未在 [最新提交](https://github.com/ClassIsland/ClassIsland/commits/dev/) 中实现
  - type: textarea
    id: back
    attributes:
      label: 背景与动机
      description: 添加此功能的理由。
    validations:
      required: true
  - type: textarea
    id: req
    attributes:
      label: 想要实现或优化的功能
      description: 详细地描述一下你想要的功能，描述的越具体，采纳的可能性越高。
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ### 最后一步：回顾您的表述
        
        - [x] 我认为上述的描述已经足够清晰，以允许开发人员理解您提出的功能。
