name: 功能请求
description: 提出一项新的功能。
title: （在这里输入你的标题）
labels: ["新功能"]
body:
  - type: markdown
    attributes:
      value: |
        感谢您贡献您的想法。请在上面的文本框⬆️起一个能够清晰概括此功能的标题，便于开发者了解您的想法。

        > 重要：如果您想要提出 **多项功能**，请为每一个功能开一个单独的 issue。
        
        ### 在开始之前，请先检查：
      
        - [x] 我已将本应用更新到最新测试版 ![最新的版本号](https://img.shields.io/github/v/release/ClassIsland/ClassIsland?include_prereleases&style=flat-square&label=)，并看过 [最新提交](https://github.com/ClassIsland/ClassIsland/commits/dev/)，确认我想要的功能还没有实现
        - [x] 我已在 [Issues](https://github.com/ClassIsland/ClassIsland/issues?q=label%3A新功能) 和 [ClassIsland 文档](https://docs.classisland.tech/zh-cn/latest/app/) 中检索，确认我想要的功能未被提交过
        - [x] 我认为我想要的功能是用户广泛需要的，且没有超出 ClassIsland 的开发目标（您可以学习 [编写插件](https://docs.classisland.tech/zh-cn/latest/dev/plugins/create-project/) 来实现特殊的需求）
  - type: textarea
    id: back
    attributes:
      label: 背景与动机
      description: 添加此功能的理由。
    validations:
      required: true
  - type: textarea
    id: req
    attributes:
      label: 想要实现或优化的功能
      description: 详细地描述一下你想要的功能，描述的越具体，采纳的可能性越高。
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ### 最后一步：回顾您的表述
        
        - [x] 我认为上述的描述已经足够清晰，以允许开发人员理解您提出的功能。
